name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: 'windows-latest'
            artifact_name: ${{ github.event.repository.name }}.exe
            asset_name: ${{ github.event.repository.name }}-windows-amd64.exe
          - os: 'ubuntu-latest'
            artifact_name: ${{ github.event.repository.name }}
            asset_name: ${{ github.event.repository.name }}-linux-amd64
          - os: 'macos-latest'
            artifact_name: ${{ github.event.repository.name }}
            asset_name: ${{ github.event.repository.name }}-macos-amd64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: |
          cd ./build
          node ./esbuild.js
          node --experimental-sea-config sea-config.json

      - name: Compile binary (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          node -e "require('fs').copyFileSync(process.execPath, 'kalliope.exe')"
          npx --yes postject kalliope.exe NODE_SEA_BLOB ./bin/sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2

      - name: Compile binary (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cp $(command -v node) kalliope
          npx --yes postject kalliope NODE_SEA_BLOB ./bin/sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2

      - name: Compile binary (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          cp $(command -v node) kalliope
          codesign --remove-signature kalliope
          npx --yes postject kalliope NODE_SEA_BLOB ./bin/sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2 --macho-segment-name NODE_SEA
          codesign --sign - kalliope

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
